steps:
  # Step 1: Terraform Init
  - name: hashicorp/terraform:1.7.7
    entrypoint: sh
    args:
      - -c
      - |
        terraform init

  # Step 2: Terraform Validate (optional but recommended)
  - name: hashicorp/terraform:1.7.7
    entrypoint: sh
    args:
      - -c
      - |
        terraform validate

  # Step 3: Terraform Plan with lock disabled
  - name: hashicorp/terraform:1.7.7
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan -out=tfplan -lock=false

  # Step 4: Terraform Apply with lock disabled
  - name: hashicorp/terraform:1.7.7
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -auto-approve -lock=false tfplan

# Service account for Cloud Build
substitutions:
  _TERRAFORM_SA: terraform-admin@my-project-mohammad-476307.iam.gserviceaccount.com

timeout: "1200s"
